// Generated by CoffeeScript 1.7.1
(function() {
  var accountKey, customerID;

  accountKey = 'o9QSUjMLDKCjfx5q30UEv3v+S+3X7dXxgClRRjeGgS4=';

  customerID = '6a59e0cf-8e49-4b12-a353-e5342feaebfe';

  exports.findImage = function(keyword) {};

}).call(this);
