// Generated by CoffeeScript 1.7.1
(function() {
  var app, db, express;

  express = require('express');

  db = require('./db');

  app = express();

  app.get('/questions', function(req, res) {
    var limit, type, _ref;
    _ref = req.query, type = _ref.type, limit = _ref.limit;
    if (limit == null) {
      limit = 10;
    }
    return db.getQuestions(type, limit).then(function(data) {
      return res.json(data);
    });
  });

  app.listen(3000);

}).call(this);
