// Generated by CoffeeScript 1.7.1
(function() {
  var app, db, express;

  express = require('express');

  db = require('./db');

  app = express();

  app.get('/', function(req, res) {
    db.getFood();
    return res.send('hello world');
  });

  app.listen(3000);

}).call(this);
